appid: 4OcLEd8QmD9HnRxrWbUHUFpV
appsecret: eXltxQ6OdjlkLupukr98TV0YUfDyaoZ5
autoshow: true
formulatype: simpletex
min2tray: true
savedir: E:\goproject\src\p2t-app\FileStorage\Image
selfupdate: false
theme: light
