// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ClipboardGetImage():Promise<string>;

export function ClipboardSetImage(arg1:string):Promise<void>;

export function DeleteByUuid(arg1:string):Promise<void>;

export function GetConfig():Promise<{[key: string]: any}>;

export function GetDataByTimeOrLatex(arg1:string,arg2:string):Promise<Array<model.LatexModel>>;

export function GetLatestDate():Promise<Array<model.LatexModel>>;

export function GetLatestReleases():Promise<Array<any>>;

export function GetTex(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function Md2Html(arg1:string):Promise<string>;

export function ParseImg(arg1:string):Promise<string>;

export function Pix2TextApi(arg1:string):Promise<string>;

export function Png2Bmp(arg1:string):Promise<string>;

export function Png2Jpeg(arg1:string):Promise<string>;

export function Png2Pdf(arg1:string):Promise<void>;

export function Png2Tiff(arg1:string):Promise<string>;

export function SimpletexApi(arg1:string):Promise<string>;

export function UpdateConfig(arg1:{[key: string]: any}):Promise<void>;
