// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardGetImage() {
  return window['go']['utils']['Utils']['ClipboardGetImage']();
}

export function ClipboardSetImage(arg1) {
  return window['go']['utils']['Utils']['ClipboardSetImage'](arg1);
}

export function DeleteByUuid(arg1) {
  return window['go']['utils']['Utils']['DeleteByUuid'](arg1);
}

export function GetConfig() {
  return window['go']['utils']['Utils']['GetConfig']();
}

export function GetDataByTimeOrLatex(arg1, arg2) {
  return window['go']['utils']['Utils']['GetDataByTimeOrLatex'](arg1, arg2);
}

export function GetLatestDate() {
  return window['go']['utils']['Utils']['GetLatestDate']();
}

export function GetLatestReleases() {
  return window['go']['utils']['Utils']['GetLatestReleases']();
}

export function GetTex(arg1) {
  return window['go']['utils']['Utils']['GetTex'](arg1);
}

export function GetVersion() {
  return window['go']['utils']['Utils']['GetVersion']();
}

export function Md2Html(arg1) {
  return window['go']['utils']['Utils']['Md2Html'](arg1);
}

export function ParseImg(arg1) {
  return window['go']['utils']['Utils']['ParseImg'](arg1);
}

export function Pix2TextApi(arg1) {
  return window['go']['utils']['Utils']['Pix2TextApi'](arg1);
}

export function Png2Bmp(arg1) {
  return window['go']['utils']['Utils']['Png2Bmp'](arg1);
}

export function Png2Jpeg(arg1) {
  return window['go']['utils']['Utils']['Png2Jpeg'](arg1);
}

export function Png2Pdf(arg1) {
  return window['go']['utils']['Utils']['Png2Pdf'](arg1);
}

export function Png2Tiff(arg1) {
  return window['go']['utils']['Utils']['Png2Tiff'](arg1);
}

export function SimpletexApi(arg1) {
  return window['go']['utils']['Utils']['SimpletexApi'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['utils']['Utils']['UpdateConfig'](arg1);
}
