// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WindowCenter():Promise<void>;

export function WindowClose(arg1:boolean):Promise<void>;

export function WindowFullScreen():Promise<void>;

export function WindowGetPosition():Promise<number|number>;

export function WindowGetSize():Promise<number|number>;

export function WindowIsFullScreen():Promise<boolean>;

export function WindowIsHidden():Promise<boolean>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowIsMinimised():Promise<boolean>;

export function WindowIsOnToped():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowOnTop():Promise<void>;

export function WindowSetPosition(arg1:number,arg2:number):Promise<void>;

export function WindowSetSize(arg1:number,arg2:number):Promise<void>;

export function WindowShowOrHide():Promise<void>;
