// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WindowCenter() {
  return window['go']['main']['App']['WindowCenter']();
}

export function WindowClose(arg1) {
  return window['go']['main']['App']['WindowClose'](arg1);
}

export function WindowFullScreen() {
  return window['go']['main']['App']['WindowFullScreen']();
}

export function WindowGetPosition() {
  return window['go']['main']['App']['WindowGetPosition']();
}

export function WindowGetSize() {
  return window['go']['main']['App']['WindowGetSize']();
}

export function WindowIsFullScreen() {
  return window['go']['main']['App']['WindowIsFullScreen']();
}

export function WindowIsHidden() {
  return window['go']['main']['App']['WindowIsHidden']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowIsMinimised() {
  return window['go']['main']['App']['WindowIsMinimised']();
}

export function WindowIsOnToped() {
  return window['go']['main']['App']['WindowIsOnToped']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowOnTop() {
  return window['go']['main']['App']['WindowOnTop']();
}

export function WindowSetPosition(arg1, arg2) {
  return window['go']['main']['App']['WindowSetPosition'](arg1, arg2);
}

export function WindowSetSize(arg1, arg2) {
  return window['go']['main']['App']['WindowSetSize'](arg1, arg2);
}

export function WindowShowOrHide() {
  return window['go']['main']['App']['WindowShowOrHide']();
}
